# Generated by Django 5.0.1 on 2026-01-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Learning"),
                            ("project", "Project-based"),
                            ("sprint", "Sprint Planning"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_columns",
                    models.JSONField(
                        default=list,
                        help_text="Default columns: ['Backlog', 'To Do', 'In Progress', 'Review', 'Done']",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kanban_boards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("position", models.IntegerField(default=0)),
                (
                    "estimated_hours",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("at_risk", "At Risk"),
                            ("blocked", "Blocked"),
                            ("overdue", "Overdue"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags: ['python', 'backend', 'urgent']",
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kanban_cards",
                "ordering": ["column", "position"],
            },
        ),
        migrations.CreateModel(
            name="CardAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="kanban/attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="kanban.card",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "kanban_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("position", models.IntegerField(default=0)),
                (
                    "wip_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Work In Progress limit (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="kanban.board",
                    ),
                ),
            ],
            options={
                "db_table": "kanban_columns",
                "ordering": ["board", "position"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="kanban.column",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="kanban.card",
                    ),
                ),
            ],
            options={
                "db_table": "kanban_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("goal", models.TextField(help_text="Sprint goal/objective")),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "planned_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "actual_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("planned_story_points", models.IntegerField(default=0)),
                ("completed_story_points", models.IntegerField(default=0)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="kanban.board",
                    ),
                ),
                (
                    "cards",
                    models.ManyToManyField(
                        blank=True, related_name="sprints", to="kanban.card"
                    ),
                ),
            ],
            options={
                "db_table": "kanban_sprints",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["owner", "is_active"], name="kanban_boar_owner_i_51a95e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["board", "position"], name="kanban_colu_board_i_430a2d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="column",
            unique_together={("board", "name")},
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["column", "position"], name="kanban_card_column__7c640d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["assigned_to", "status"], name="kanban_card_assigne_463fa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["due_date"], name="kanban_card_due_dat_e1e402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["board", "is_active"], name="kanban_spri_board_i_fbd367_idx"
            ),
        ),
    ]
