# Generated by Django 5.0.1 on 2026-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
